name = "ArtificialTheorems"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["ArtificialTheorems"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.23.0"

[[require]]
name = "SafeVerify"
git = "https://github.com/GasStationManager/SafeVerify.git"
rev = "main"

[[require]]
name = "lean4checker"
scope = "leanprover"
rev = "v4.23.0"

[[lean_lib]]
name = "ArtificialTheorems"

[[lean_lib]]
name = "ArtificialTheoremsSpec"
